name: "CD: Terraform Apply (Main Merge)"

on:
  push:
    branches:
      - main

permissions:
  contents: read

env:
  TERRAFORM_VERSION: 1.6.0
  AWS_REGION: ${{ secrets.AWS_REGION }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}


jobs:
  terraform-apply:
    name: "Terraform Apply"
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: terraform

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}
          terraform_wrapper: false

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Init
        run: terraform init -input=false

      - name: Terraform Plan (prod)
        id: plan-prod
        run: terraform plan -input=false -out=tfplan-prod

      - name: Upload Prod Plan
        uses: actions/upload-artifact@v4
        with:
          name: prod-plan
          path: terraform/tfplan-prod
          retention-days: 5

      - name: Terraform Apply (prod)
        id: apply-prod
        run: terraform apply -input=false -auto-approve tfplan-prod

      - name: Get Outputs
        id: outputs
        run: terraform output

      - name: Notify / Audit Logging
        run: |
          # Example: echo commit SHA, who merged, timestamp
          echo "Deployed prod environment at commit ${{ github.sha }} by ${{ github.actor }}"